services:
  web:
    build: .
    ports:
      - "8000:8000"
    environment:
      DJANGO_DEBUG: "True"
      DJANGO_ALLOWED_HOSTS: "127.0.0.1,localhost,0.0.0.0"
      DJANGO_DATABASE_NAME: "/data/db.sqlite3"
    volumes:
      - attendance_db:/data
      - attendance_media:/app/media

volumes:
  attendance_db:
  attendance_media:
